apiVersion: skaffold/2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: fgyimah/auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
